#!/bin/bash

nbfichier=0
nbdir=0
for i in `ls`
do
	if [ -d $i ]
		then
			nbdir=$((nbdir+1))
	elif [ -f $i ]
		then
			nbfichier=$((nbfichier+1))
	fi
done

echo "Nombre de répertoires : $nbdir"
echo "Nombre de fichiers : $nbfichier"
